// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG3sJehcSGNoLJ0rIhuDUMMzmHp5q-IJ4',
    appId: '1:201197161177:web:6012843c4f7fd0a6670cc8',
    messagingSenderId: '201197161177',
    projectId: 'klay-app-e4ba2',
    authDomain: 'klay-app-e4ba2.firebaseapp.com',
    storageBucket: 'klay-app-e4ba2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_TKzzDTN3WbJBoDzif3tu7GsfHTVDbKQ',
    appId: '1:201197161177:android:31ce06bcaa52012c670cc8',
    messagingSenderId: '201197161177',
    projectId: 'klay-app-e4ba2',
    storageBucket: 'klay-app-e4ba2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnfJMD7OTUuknUyt9eUKZAiH0lOed0poM',
    appId: '1:201197161177:ios:23922a90ec08ffb0670cc8',
    messagingSenderId: '201197161177',
    projectId: 'klay-app-e4ba2',
    storageBucket: 'klay-app-e4ba2.firebasestorage.app',
    iosBundleId: 'com.example.klay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnfJMD7OTUuknUyt9eUKZAiH0lOed0poM',
    appId: '1:201197161177:ios:23922a90ec08ffb0670cc8',
    messagingSenderId: '201197161177',
    projectId: 'klay-app-e4ba2',
    storageBucket: 'klay-app-e4ba2.firebasestorage.app',
    iosBundleId: 'com.example.klay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG3sJehcSGNoLJ0rIhuDUMMzmHp5q-IJ4',
    appId: '1:201197161177:web:311aa3edb3680bd2670cc8',
    messagingSenderId: '201197161177',
    projectId: 'klay-app-e4ba2',
    authDomain: 'klay-app-e4ba2.firebaseapp.com',
    storageBucket: 'klay-app-e4ba2.firebasestorage.app',
  );
}
